/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author TASS
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContainer = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        pnContainer.setPreferredSize(new java.awt.Dimension(500, 700));

        jTextField1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("All Clear");

        btn3.setBackground(new java.awt.Color(255, 219, 132));
        btn3.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn3.setText("MR");
        btn3.setToolTipText("");
        btn3.setMaximumSize(new java.awt.Dimension(80, 80));
        btn3.setMinimumSize(new java.awt.Dimension(80, 80));
        btn3.setPreferredSize(new java.awt.Dimension(80, 80));
        btn3.setRequestFocusEnabled(false);

        btn5.setBackground(new java.awt.Color(255, 219, 132));
        btn5.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn5.setText("MR");
        btn5.setToolTipText("");
        btn5.setMaximumSize(new java.awt.Dimension(80, 80));
        btn5.setMinimumSize(new java.awt.Dimension(80, 80));
        btn5.setPreferredSize(new java.awt.Dimension(80, 80));
        btn5.setRequestFocusEnabled(false);

        btn9.setBackground(new java.awt.Color(255, 219, 132));
        btn9.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn9.setText("MR");
        btn9.setToolTipText("");
        btn9.setMaximumSize(new java.awt.Dimension(80, 80));
        btn9.setMinimumSize(new java.awt.Dimension(80, 80));
        btn9.setPreferredSize(new java.awt.Dimension(80, 80));
        btn9.setRequestFocusEnabled(false);

        btn10.setBackground(new java.awt.Color(255, 219, 132));
        btn10.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn10.setText("MR");
        btn10.setToolTipText("");
        btn10.setMaximumSize(new java.awt.Dimension(80, 80));
        btn10.setMinimumSize(new java.awt.Dimension(80, 80));
        btn10.setPreferredSize(new java.awt.Dimension(80, 80));
        btn10.setRequestFocusEnabled(false);

        btn11.setBackground(new java.awt.Color(103, 254, 118));
        btn11.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn11.setText("MR");
        btn11.setToolTipText("");
        btn11.setMaximumSize(new java.awt.Dimension(80, 80));
        btn11.setMinimumSize(new java.awt.Dimension(80, 80));
        btn11.setPreferredSize(new java.awt.Dimension(80, 80));
        btn11.setRequestFocusEnabled(false);

        btn4.setBackground(new java.awt.Color(195, 208, 254));
        btn4.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn4.setText("MR");
        btn4.setToolTipText("");
        btn4.setMaximumSize(new java.awt.Dimension(80, 80));
        btn4.setMinimumSize(new java.awt.Dimension(80, 80));
        btn4.setPreferredSize(new java.awt.Dimension(80, 80));
        btn4.setRequestFocusEnabled(false);

        btn6.setBackground(new java.awt.Color(195, 208, 254));
        btn6.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn6.setText("MR");
        btn6.setToolTipText("");
        btn6.setMaximumSize(new java.awt.Dimension(80, 80));
        btn6.setMinimumSize(new java.awt.Dimension(80, 80));
        btn6.setPreferredSize(new java.awt.Dimension(80, 80));
        btn6.setRequestFocusEnabled(false);

        btn12.setBackground(new java.awt.Color(195, 208, 254));
        btn12.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn12.setText("MR");
        btn12.setToolTipText("");
        btn12.setMaximumSize(new java.awt.Dimension(80, 80));
        btn12.setMinimumSize(new java.awt.Dimension(80, 80));
        btn12.setPreferredSize(new java.awt.Dimension(80, 80));
        btn12.setRequestFocusEnabled(false);

        btn13.setBackground(new java.awt.Color(103, 254, 118));
        btn13.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn13.setText("MR");
        btn13.setToolTipText("");
        btn13.setMaximumSize(new java.awt.Dimension(80, 80));
        btn13.setMinimumSize(new java.awt.Dimension(80, 80));
        btn13.setPreferredSize(new java.awt.Dimension(80, 80));
        btn13.setRequestFocusEnabled(false);

        btn14.setBackground(new java.awt.Color(103, 254, 118));
        btn14.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn14.setText("MR");
        btn14.setToolTipText("");
        btn14.setMaximumSize(new java.awt.Dimension(80, 80));
        btn14.setMinimumSize(new java.awt.Dimension(80, 80));
        btn14.setPreferredSize(new java.awt.Dimension(80, 80));
        btn14.setRequestFocusEnabled(false);

        btn7.setBackground(new java.awt.Color(195, 208, 254));
        btn7.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn7.setText("MR");
        btn7.setToolTipText("");
        btn7.setMaximumSize(new java.awt.Dimension(80, 80));
        btn7.setMinimumSize(new java.awt.Dimension(80, 80));
        btn7.setPreferredSize(new java.awt.Dimension(80, 80));
        btn7.setRequestFocusEnabled(false);

        btn8.setBackground(new java.awt.Color(195, 208, 254));
        btn8.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn8.setText("MR");
        btn8.setToolTipText("");
        btn8.setMaximumSize(new java.awt.Dimension(80, 80));
        btn8.setMinimumSize(new java.awt.Dimension(80, 80));
        btn8.setPreferredSize(new java.awt.Dimension(80, 80));
        btn8.setRequestFocusEnabled(false);

        btn15.setBackground(new java.awt.Color(195, 208, 254));
        btn15.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn15.setText("MR");
        btn15.setToolTipText("");
        btn15.setMaximumSize(new java.awt.Dimension(80, 80));
        btn15.setMinimumSize(new java.awt.Dimension(80, 80));
        btn15.setPreferredSize(new java.awt.Dimension(80, 80));
        btn15.setRequestFocusEnabled(false);

        btn16.setBackground(new java.awt.Color(195, 208, 254));
        btn16.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn16.setText("MR");
        btn16.setToolTipText("");
        btn16.setMaximumSize(new java.awt.Dimension(80, 80));
        btn16.setMinimumSize(new java.awt.Dimension(80, 80));
        btn16.setPreferredSize(new java.awt.Dimension(80, 80));
        btn16.setRequestFocusEnabled(false);

        btn17.setBackground(new java.awt.Color(195, 208, 254));
        btn17.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn17.setText("MR");
        btn17.setToolTipText("");
        btn17.setMaximumSize(new java.awt.Dimension(80, 80));
        btn17.setMinimumSize(new java.awt.Dimension(80, 80));
        btn17.setPreferredSize(new java.awt.Dimension(80, 80));
        btn17.setRequestFocusEnabled(false);

        btn18.setBackground(new java.awt.Color(195, 208, 254));
        btn18.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn18.setText("MR");
        btn18.setToolTipText("");
        btn18.setMaximumSize(new java.awt.Dimension(80, 80));
        btn18.setMinimumSize(new java.awt.Dimension(80, 80));
        btn18.setPreferredSize(new java.awt.Dimension(80, 80));
        btn18.setRequestFocusEnabled(false);

        btn19.setBackground(new java.awt.Color(103, 254, 118));
        btn19.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn19.setText("MR");
        btn19.setToolTipText("");
        btn19.setMaximumSize(new java.awt.Dimension(80, 80));
        btn19.setMinimumSize(new java.awt.Dimension(80, 80));
        btn19.setPreferredSize(new java.awt.Dimension(80, 80));
        btn19.setRequestFocusEnabled(false);

        btn20.setBackground(new java.awt.Color(103, 254, 118));
        btn20.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn20.setText("MR");
        btn20.setToolTipText("");
        btn20.setMaximumSize(new java.awt.Dimension(80, 80));
        btn20.setMinimumSize(new java.awt.Dimension(80, 80));
        btn20.setPreferredSize(new java.awt.Dimension(80, 80));
        btn20.setRequestFocusEnabled(false);

        btn21.setBackground(new java.awt.Color(103, 254, 118));
        btn21.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn21.setText("MR");
        btn21.setToolTipText("");
        btn21.setMaximumSize(new java.awt.Dimension(80, 80));
        btn21.setMinimumSize(new java.awt.Dimension(80, 80));
        btn21.setPreferredSize(new java.awt.Dimension(80, 80));
        btn21.setRequestFocusEnabled(false);

        btn22.setBackground(new java.awt.Color(103, 254, 118));
        btn22.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn22.setText("MR");
        btn22.setToolTipText("");
        btn22.setMaximumSize(new java.awt.Dimension(80, 80));
        btn22.setMinimumSize(new java.awt.Dimension(80, 80));
        btn22.setPreferredSize(new java.awt.Dimension(80, 80));
        btn22.setRequestFocusEnabled(false);

        btn24.setBackground(new java.awt.Color(103, 254, 118));
        btn24.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn24.setText("MR");
        btn24.setToolTipText("");
        btn24.setMaximumSize(new java.awt.Dimension(80, 80));
        btn24.setMinimumSize(new java.awt.Dimension(80, 80));
        btn24.setPreferredSize(new java.awt.Dimension(80, 80));
        btn24.setRequestFocusEnabled(false);

        btn25.setBackground(new java.awt.Color(103, 254, 118));
        btn25.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn25.setText("MR");
        btn25.setToolTipText("");
        btn25.setMaximumSize(new java.awt.Dimension(80, 80));
        btn25.setMinimumSize(new java.awt.Dimension(80, 80));
        btn25.setPreferredSize(new java.awt.Dimension(80, 80));
        btn25.setRequestFocusEnabled(false);

        btn26.setBackground(new java.awt.Color(195, 208, 254));
        btn26.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn26.setText("MR");
        btn26.setToolTipText("");
        btn26.setMaximumSize(new java.awt.Dimension(80, 80));
        btn26.setMinimumSize(new java.awt.Dimension(80, 80));
        btn26.setPreferredSize(new java.awt.Dimension(80, 80));
        btn26.setRequestFocusEnabled(false);

        btn27.setBackground(new java.awt.Color(195, 208, 254));
        btn27.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        btn27.setText("MR");
        btn27.setToolTipText("");
        btn27.setMaximumSize(new java.awt.Dimension(80, 80));
        btn27.setMinimumSize(new java.awt.Dimension(80, 80));
        btn27.setPreferredSize(new java.awt.Dimension(80, 80));
        btn27.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnContainerLayout = new javax.swing.GroupLayout(pnContainer);
        pnContainer.setLayout(pnContainerLayout);
        pnContainerLayout.setHorizontalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainerLayout.createSequentialGroup()
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContainerLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnContainerLayout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnContainerLayout.createSequentialGroup()
                                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnContainerLayout.createSequentialGroup()
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnContainerLayout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnContainerLayout.createSequentialGroup()
                                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnContainerLayout.createSequentialGroup()
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnContainerLayout.createSequentialGroup()
                                        .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnContainerLayout.setVerticalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnContainer;
    // End of variables declaration//GEN-END:variables
}
